name: Bug / Problema con el estilo
description: Report a formatting problem with the CSL style
title: "[BUG] "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ## 游쀯릖 Espa침ol
        Complet치 la informaci칩n para que podamos reproducir el problema.

        ## 游섫릖 English
        Please provide enough details so we can reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: 쯈u칠 est치 pasando? / What is happening?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 쯈u칠 esperabas obtener? / Expected result
      description: Mostr치/Show the correct formatting
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Resultado actual / Actual result
    validations:
      required: true

  - type: dropdown
    id: manager
    attributes:
      label: Gestor o motor de citas / Citation manager
      options:
        - Zotero
        - Mendeley
        - Pandoc / citeproc
        - Quarto
        - LaTeX / BibLaTeX
        - Otro / Other
    validations:
      required: true

  - type: dropdown
    id: format
    attributes:
      label: Formato del archivo / Reference format
      options:
        - .bib (BibTeX)
        - .json (CSL JSON)
        - .ris
        - .xml
        - Otro / Other
    validations:
      required: true

  - type: textarea
    id: sample
    attributes:
      label: Registro m칤nimo / Minimal reference sample
      description: Peg치 SOLO el 칤tem problem치tico / Paste ONLY the problematic entry
      render: text
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Versi칩n del estilo / Style version (commit/tag)
