name: Pregunta / Question
description: Ask how to use the style or clarify behavior
title: "[QUESTION] "
labels: ["question"]

body:
  - type: textarea
    id: question
    attributes:
      label: Pregunta / Question
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexto adicional / Additional context
      description: gestor, formato, captura, etc.
